-- Run once as NFE_OWNER in PDB_POCRT_02.
-- Creates only PoC control and sample-source structures. It never deletes an
-- existing NF-e row or changes XML_CLOB content.

whenever sqlerror exit failure rollback
set serveroutput on size unlimited

create table poc_nfe_document (
  nfe_id            number generated by default as identity,
  chave_nfe         varchar2(44 char) not null,
  emitente_cnpj     varchar2(14 char),
  destinatario_cnpj varchar2(14 char),
  data_emissao      timestamp(6) with time zone not null,
  situacao          varchar2(30 char) not null,
  xml_clob          clob,
  created_at        timestamp(6) with time zone default systimestamp not null,
  constraint pk_poc_nfe_document primary key (nfe_id),
  constraint uk_poc_nfe_document_chave unique (chave_nfe)
)
lob (xml_clob) store as securefile poc_nfe_xml_lob;

create index ix_poc_nfe_document_emissao
  on poc_nfe_document (data_emissao, nfe_id);

create table nfe_migration_batch (
  batch_id                number generated by default as identity,
  batch_code              varchar2(50 char) not null,
  status                  varchar2(30 char) not null,
  cutoff_date             timestamp(6) with time zone not null,
  max_documents           number not null,
  selection_chunk_size    number default 1000 not null,
  criteria_json           clob not null,
  selected_count          number default 0 not null,
  queued_count            number default 0 not null,
  uploaded_count          number default 0 not null,
  verified_count          number default 0 not null,
  failed_count            number default 0 not null,
  exception_count         number default 0 not null,
  purged_count            number default 0 not null,
  source_bytes            number default 0 not null,
  object_bytes            number default 0 not null,
  created_by              varchar2(128 char) not null,
  created_at              timestamp(6) with time zone default systimestamp not null,
  selection_completed_at  timestamp(6) with time zone,
  reconciliation_status   varchar2(30 char),
  reconciled_at           timestamp(6) with time zone,
  approved_by             varchar2(128 char),
  approved_at             timestamp(6) with time zone,
  approval_comment        varchar2(1000 char),
  approval_evidence_ref   varchar2(2000 char),
  purge_started_at        timestamp(6) with time zone,
  purged_at               timestamp(6) with time zone,
  last_error              varchar2(4000 char),
  constraint pk_nfe_migration_batch primary key (batch_id),
  constraint uk_nfe_migration_batch_code unique (batch_code),
  constraint ck_nfe_migration_batch_status check (status in (
    'CREATED', 'SELECTING', 'PROCESSING', 'RECONCILING',
    'READY_FOR_APPROVAL', 'APPROVED_FOR_PURGE', 'PURGING',
    'PURGED', 'BLOCKED', 'CANCELLED')),
  constraint ck_nfe_migration_batch_limit check (max_documents > 0),
  constraint ck_nfe_migration_batch_chunk check (selection_chunk_size > 0),
  constraint ck_nfe_migration_batch_counts check (
    selected_count >= 0 and queued_count >= 0 and uploaded_count >= 0 and
    verified_count >= 0 and failed_count >= 0 and exception_count >= 0 and
    purged_count >= 0 and source_bytes >= 0 and object_bytes >= 0),
  constraint ck_nfe_migration_batch_approval check (
    (approved_by is null and approved_at is null and approval_comment is null and approval_evidence_ref is null)
    or
    (approved_by is not null and approved_at is not null and approval_comment is not null and approval_evidence_ref is not null)),
  constraint ck_nfe_migration_batch_json check (criteria_json is json)
);

create table nfe_migration_item (
  control_id         number generated by default as identity,
  batch_id           number not null,
  nfe_id             number not null,
  status             varchar2(30 char) not null,
  object_key         varchar2(1024 char) not null,
  object_uri         varchar2(2000 char) not null,
  content_type       varchar2(100 char) default 'application/xml' not null,
  charset_name       varchar2(30 char) default 'AL32UTF8' not null,
  source_size_bytes  number,
  object_size_bytes  number,
  source_sha256      varchar2(64 char),
  object_sha256      varchar2(64 char),
  etag               varchar2(256 char),
  object_version_id  varchar2(512 char),
  aq_msgid           raw(16),
  business_attempts  number default 0 not null,
  selected_at        timestamp(6) with time zone default systimestamp not null,
  enqueued_at        timestamp(6) with time zone,
  upload_started_at  timestamp(6) with time zone,
  uploaded_at        timestamp(6) with time zone,
  verified_at        timestamp(6) with time zone,
  purged_at          timestamp(6) with time zone,
  last_error_code    varchar2(100 char),
  last_error         varchar2(4000 char),
  last_error_at      timestamp(6) with time zone,
  created_at         timestamp(6) with time zone default systimestamp not null,
  updated_at         timestamp(6) with time zone default systimestamp not null,
  constraint pk_nfe_migration_item primary key (control_id),
  constraint fk_nfe_migration_item_batch foreign key (batch_id)
    references nfe_migration_batch (batch_id),
  constraint fk_nfe_migration_item_nfe foreign key (nfe_id)
    references poc_nfe_document (nfe_id),
  constraint uk_nfe_migration_item_nfe unique (nfe_id),
  constraint uk_nfe_migration_item_key unique (object_key),
  constraint ck_nfe_migration_item_status check (status in (
    'QUEUED', 'UPLOADING', 'UPLOADED', 'VERIFYING', 'VERIFIED',
    'FAILED', 'EXCEPTION', 'PURGED')),
  constraint ck_nfe_migration_item_attempts check (business_attempts >= 0),
  constraint ck_nfe_migration_item_sizes check (
    (source_size_bytes is null or source_size_bytes >= 0) and
    (object_size_bytes is null or object_size_bytes >= 0))
);

create index ix_nfe_migration_item_batch_status
  on nfe_migration_item (batch_id, status, control_id);

create index ix_nfe_migration_item_status
  on nfe_migration_item (status, updated_at);

create table nfe_migration_audit (
  audit_id        number generated by default as identity,
  event_at        timestamp(6) with time zone default systimestamp not null,
  actor           varchar2(128 char) not null,
  actor_type      varchar2(30 char) not null,
  batch_id        number,
  control_id      number,
  event_type      varchar2(50 char) not null,
  from_status     varchar2(30 char),
  to_status       varchar2(30 char),
  correlation_id  varchar2(100 char),
  details_json    clob,
  constraint pk_nfe_migration_audit primary key (audit_id),
  constraint fk_nfe_migration_audit_batch foreign key (batch_id)
    references nfe_migration_batch (batch_id),
  constraint fk_nfe_migration_audit_item foreign key (control_id)
    references nfe_migration_item (control_id),
  constraint ck_nfe_migration_audit_actor check (
    actor_type in ('USER', 'SCHEDULER', 'WORKER', 'SYSTEM')),
  constraint ck_nfe_migration_audit_json check (details_json is json)
);

create index ix_nfe_migration_audit_batch
  on nfe_migration_audit (batch_id, event_at);

create index ix_nfe_migration_audit_item
  on nfe_migration_audit (control_id, event_at);

create table nfe_reconciliation_run (
  reconciliation_id       number generated by default as identity,
  batch_id                number not null,
  status                  varchar2(20 char) not null,
  total_count             number default 0 not null,
  verified_count          number default 0 not null,
  missing_object_count    number default 0 not null,
  size_mismatch_count     number default 0 not null,
  hash_mismatch_count     number default 0 not null,
  failed_count            number default 0 not null,
  exception_count         number default 0 not null,
  source_bytes            number default 0 not null,
  object_bytes            number default 0 not null,
  report_uri              varchar2(2000 char),
  started_at              timestamp(6) with time zone default systimestamp not null,
  completed_at            timestamp(6) with time zone,
  executed_by             varchar2(128 char) not null,
  constraint pk_nfe_reconciliation_run primary key (reconciliation_id),
  constraint fk_nfe_reconciliation_batch foreign key (batch_id)
    references nfe_migration_batch (batch_id),
  constraint ck_nfe_reconciliation_status check (status in ('RUNNING', 'PASSED', 'FAILED')),
  constraint ck_nfe_reconciliation_counts check (
    total_count >= 0 and verified_count >= 0 and missing_object_count >= 0 and
    size_mismatch_count >= 0 and hash_mismatch_count >= 0 and failed_count >= 0 and
    exception_count >= 0 and source_bytes >= 0 and object_bytes >= 0)
);

create index ix_nfe_reconciliation_batch
  on nfe_reconciliation_run (batch_id, started_at);

create table nfe_migration_config (
  config_id               number not null,
  pipeline_paused         char(1 char) default 'N' not null,
  max_inflight_messages   number default 10000 not null,
  enqueue_chunk_size      number default 1000 not null,
  worker_count            number default 2 not null,
  worker_idle_seconds     number default 5 not null,
  max_worker_run_minutes  number default 30 not null,
  updated_by              varchar2(128 char) not null,
  updated_at              timestamp(6) with time zone default systimestamp not null,
  constraint pk_nfe_migration_config primary key (config_id),
  constraint ck_nfe_migration_config_singleton check (config_id = 1),
  constraint ck_nfe_migration_paused check (pipeline_paused in ('Y', 'N')),
  constraint ck_nfe_migration_inflight check (max_inflight_messages > 0),
  constraint ck_nfe_migration_chunk check (enqueue_chunk_size > 0),
  constraint ck_nfe_migration_workers check (worker_count > 0),
  constraint ck_nfe_migration_idle check (worker_idle_seconds > 0),
  constraint ck_nfe_migration_runtime check (max_worker_run_minutes > 0)
);

insert into nfe_migration_config (config_id, updated_by)
values (1, sys_context('USERENV', 'SESSION_USER'));

create or replace trigger trg_nfe_item_updated_at
before update on nfe_migration_item
for each row
begin
  :new.updated_at := systimestamp;
end;
/

create or replace trigger trg_nfe_item_status_transition
before insert or update of status on nfe_migration_item
for each row
begin
  if inserting then
    if :new.status <> 'QUEUED' then
      raise_application_error(-20010, 'A migration item must be created in QUEUED status.');
    end if;
  elsif not (
       (:old.status = 'QUEUED' and :new.status in ('UPLOADING', 'EXCEPTION'))
    or (:old.status = 'UPLOADING' and :new.status in ('UPLOADED', 'FAILED', 'EXCEPTION'))
    or (:old.status = 'UPLOADED' and :new.status in ('VERIFYING', 'FAILED', 'EXCEPTION'))
    or (:old.status = 'VERIFYING' and :new.status in ('VERIFIED', 'FAILED', 'EXCEPTION'))
    or (:old.status = 'VERIFIED' and :new.status = 'PURGED')
    or (:old.status in ('FAILED', 'EXCEPTION') and :new.status = 'QUEUED')
    or :old.status = :new.status) then
    raise_application_error(-20011, 'Invalid NFE migration item status transition.');
  end if;
end;
/

create or replace trigger trg_nfe_batch_status_transition
before insert or update of status on nfe_migration_batch
for each row
begin
  if inserting then
    if :new.status <> 'CREATED' then
      raise_application_error(-20012, 'A migration batch must be created in CREATED status.');
    end if;
  elsif not (
       (:old.status = 'CREATED' and :new.status in ('SELECTING', 'CANCELLED'))
    or (:old.status = 'SELECTING' and :new.status in ('PROCESSING', 'RECONCILING', 'BLOCKED', 'CANCELLED'))
    or (:old.status = 'PROCESSING' and :new.status in ('RECONCILING', 'BLOCKED'))
    or (:old.status = 'RECONCILING' and :new.status in ('READY_FOR_APPROVAL', 'BLOCKED'))
    or (:old.status = 'READY_FOR_APPROVAL' and :new.status in ('APPROVED_FOR_PURGE', 'BLOCKED'))
    or (:old.status = 'APPROVED_FOR_PURGE' and :new.status in ('PURGING', 'BLOCKED'))
    or (:old.status = 'PURGING' and :new.status in ('PURGED', 'BLOCKED'))
    or (:old.status = 'BLOCKED' and :new.status in ('SELECTING', 'PROCESSING', 'RECONCILING', 'READY_FOR_APPROVAL'))
    or :old.status = :new.status) then
    raise_application_error(-20013, 'Invalid NFE migration batch status transition.');
  end if;
end;
/

create or replace trigger trg_nfe_audit_append_only
before update or delete on nfe_migration_audit
begin
  raise_application_error(-20014, 'NFE_MIGRATION_AUDIT is append-only.');
end;
/

prompt PASS: NFE migration PoC schema created under NFE_OWNER.
